/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Secretary;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import models.NewAppointmentRequest;

/**
 *
 * @author richa_bfe6tpy
 */
public class SecretaryApproveAppointmentView extends javax.swing.JPanel {

    /**
     * Creates new form SecretaryApproveAppointmentView
     */
    public SecretaryApproveAppointmentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SecretaryApprovePatientLabel = new javax.swing.JLabel();
        SecretaryApprovePatientBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SecretaryApprovePatientListBox = new javax.swing.JList<>();
        SecretaryApprovePatientApproveButton = new javax.swing.JButton();
        SecretaryApprovePatientDeclineButton = new javax.swing.JButton();

        SecretaryApprovePatientLabel.setText("Approve Patient Appointments");

        SecretaryApprovePatientBackButton.setText("Back");

        SecretaryApprovePatientListBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(SecretaryApprovePatientListBox);

        SecretaryApprovePatientApproveButton.setText("Approve");

        SecretaryApprovePatientDeclineButton.setText("Decline");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(SecretaryApprovePatientLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(185, 185, 185))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SecretaryApprovePatientBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SecretaryApprovePatientDeclineButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecretaryApprovePatientApproveButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(SecretaryApprovePatientLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecretaryApprovePatientBackButton)
                    .addComponent(SecretaryApprovePatientApproveButton)
                    .addComponent(SecretaryApprovePatientDeclineButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addAcceptListener(ActionListener listenForSecretaryApproveAppointment){
        SecretaryApprovePatientApproveButton.addActionListener(listenForSecretaryApproveAppointment);
    }
    
    public void addBackListener(ActionListener listenForBack){
        SecretaryApprovePatientBackButton.addActionListener(listenForBack);
    }
    
    public void addDeclineListener(ActionListener listenForSecretaryDeclineAppointment){
        SecretaryApprovePatientDeclineButton.addActionListener(listenForSecretaryDeclineAppointment);
    }
    
    public NewAppointmentRequest getSelectedAppointmentRequest(){
        NewAppointmentRequest newAppointmentRequest = SecretaryApprovePatientListBox.getSelectedValue();
        return newAppointmentRequest;
    }

    public void setAppointmentsRequests(DefaultListModel<NewAppointmentRequest> model){
        SecretaryApprovePatientListBox.setModel(model);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SecretaryApprovePatientApproveButton;
    private javax.swing.JButton SecretaryApprovePatientBackButton;
    private javax.swing.JButton SecretaryApprovePatientDeclineButton;
    private javax.swing.JLabel SecretaryApprovePatientLabel;
    private javax.swing.JList<NewAppointmentRequest> SecretaryApprovePatientListBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
