/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Secretary;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JScrollPane;
import models.NewAccountRequest;

/**
 *
 * @author richa_bfe6tpy
 */

//This class provide a panel which contains the Secretary approve patient view.
public class SecretaryApprovePatientView extends javax.swing.JPanel {

    private JButton SecretaryApprovePatientButton;
    private JScrollPane jScrollPane1;
    private JList<NewAccountRequest> SecretaryAccountRequestedList;
    private JButton SecretaryDeclinePatientButton;
    private JButton SecretaryBackButton;

    /**
     * Creates new form SecrataryApprovePatientView
     */
    public SecretaryApprovePatientView() {
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    //View setup code
    private void initMyComponents() {
        SecretaryApprovePatientButton = new javax.swing.JButton();
        SecretaryDeclinePatientButton = new javax.swing.JButton();
        SecretaryBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SecretaryAccountRequestedList = new javax.swing.JList<>();
        
        
        
        
        SecretaryApprovePatientButton.setText("Approve");
        SecretaryDeclinePatientButton.setText("Decline");
        SecretaryBackButton.setText("Back");        
       

        SecretaryAccountRequestedList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SecretaryAccountRequestedList.setToolTipText("");
        jScrollPane1.setViewportView(SecretaryAccountRequestedList);

        javax.swing.GroupLayout SecretaryApprovePatientPanelLayout = new javax.swing.GroupLayout(this);
        this.setLayout(SecretaryApprovePatientPanelLayout);
        SecretaryApprovePatientPanelLayout.setHorizontalGroup(
            SecretaryApprovePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            
            .addGroup(SecretaryApprovePatientPanelLayout.createSequentialGroup()
                 .addGap(30, 30, 30)
                 .addComponent(SecretaryBackButton)   
            
            )
            .addGroup(SecretaryApprovePatientPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1)
                .addGap(22, 22, 22)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SecretaryApprovePatientPanelLayout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(SecretaryDeclinePatientButton)
                .addComponent(SecretaryApprovePatientButton)
                
                .addGap(180, 180, 180))
        );
        SecretaryApprovePatientPanelLayout.setVerticalGroup(
            SecretaryApprovePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecretaryApprovePatientPanelLayout.createSequentialGroup()
                 .addComponent(SecretaryBackButton)   
            
            )
            .addGroup(SecretaryApprovePatientPanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SecretaryApprovePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(SecretaryApprovePatientButton)
                    .addComponent(SecretaryDeclinePatientButton))
                .addContainerGap())
        );
    }

    
    //Button Listeners 

    public void addSubmitListener(ActionListener listenForSecretaryApprovePatient){
        SecretaryApprovePatientButton.addActionListener(listenForSecretaryApprovePatient);
    }
    
    public void addBackListener(ActionListener listenForBack){
        SecretaryBackButton.addActionListener(listenForBack);
    }
    
    public void addDeclineListener(ActionListener listenForSecretaryDeclinePatient){
        SecretaryDeclinePatientButton.addActionListener(listenForSecretaryDeclinePatient);
    }
    
    //Set NewAccountRequest list Model and get NewAccountRequest element
    
    public NewAccountRequest getSelectedUserRequest(){
        NewAccountRequest newAccountRequest = SecretaryAccountRequestedList.getSelectedValue();
        return newAccountRequest;
    }

    public void setUserRequests(DefaultListModel<NewAccountRequest> model){
        SecretaryAccountRequestedList.setModel(model);
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
