/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Admin;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import models.user.User;

/**
 *
 * @author richa_bfe6tpy
 */
public class AdminModifyDoctorsView extends javax.swing.JPanel {

    /**
     * Creates new form AdminModifyDoctorsView
     */
    public AdminModifyDoctorsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AdminModifyDoctorsListBox = new javax.swing.JList<>();
        AdminModifyDoctorDeleteButton = new javax.swing.JButton();
        AdminModifyDoctorsLabel = new javax.swing.JLabel();

        AdminBackButton.setText("Back");

        AdminModifyDoctorsListBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(AdminModifyDoctorsListBox);

        AdminModifyDoctorDeleteButton.setText("Delete");

        AdminModifyDoctorsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminModifyDoctorsLabel.setText("Select Doctor To Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(AdminModifyDoctorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AdminBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdminModifyDoctorDeleteButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(AdminModifyDoctorsLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminBackButton)
                    .addComponent(AdminModifyDoctorDeleteButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addBackListener(ActionListener listenForSubmit){
        AdminBackButton.addActionListener(listenForSubmit);
    }
    
    public void addDeleteListener(ActionListener listenForDelete){
        AdminModifyDoctorDeleteButton.addActionListener(listenForDelete);
    }
    
    public User getSelectedUser(){
        User user = AdminModifyDoctorsListBox.getSelectedValue();
        return user;
    }
    
    public void clearList()
    {
        AdminModifyDoctorsListBox.removeAll();
    }
    
    public void setDoctorList(DefaultListModel<User> users)
    {
        AdminModifyDoctorsListBox.setModel(users);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBackButton;
    private javax.swing.JButton AdminModifyDoctorDeleteButton;
    private javax.swing.JLabel AdminModifyDoctorsLabel;
    private javax.swing.JList<User> AdminModifyDoctorsListBox;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
