/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Admin;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import models.user.Doctor;

/**
 *
 * @author richa_bfe6tpy
 */
public class AdminDoctorFeedBackView extends javax.swing.JPanel {

    /**
     * Creates new form AdminDoctorFeedBackView
     */
    public AdminDoctorFeedBackView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminBackButton = new javax.swing.JButton();
        AdminDoctorFeedBackDoctorBox = new javax.swing.JComboBox<>();
        AdminDoctorFeedBackLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AdminDoctorFeedBackBox = new javax.swing.JTextArea();
        AdminDoctorFeedBackSubmitButton = new javax.swing.JButton();

        AdminBackButton.setText("Back");

        AdminDoctorFeedBackLabel.setText("Doctor");

        AdminDoctorFeedBackBox.setEditable(false);
        AdminDoctorFeedBackBox.setBackground(new java.awt.Color(240, 240, 240));
        AdminDoctorFeedBackBox.setColumns(20);
        AdminDoctorFeedBackBox.setRows(5);
        jScrollPane1.setViewportView(AdminDoctorFeedBackBox);

        AdminDoctorFeedBackSubmitButton.setText("Generate Feedback");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(AdminDoctorFeedBackDoctorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(AdminDoctorFeedBackLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDoctorFeedBackSubmitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(AdminDoctorFeedBackLabel)
                .addGap(18, 18, 18)
                .addComponent(AdminDoctorFeedBackDoctorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminBackButton)
                    .addComponent(AdminDoctorFeedBackSubmitButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void addBackListener(ActionListener listenForSubmit){
        AdminBackButton.addActionListener(listenForSubmit);
    }
    
    public void addGenerateFeedBackListener(ActionListener listenForFeedBack){
        AdminDoctorFeedBackSubmitButton.addActionListener(listenForFeedBack);
    } 
    
    public Doctor getDoctor(){
        return (Doctor) AdminDoctorFeedBackDoctorBox.getSelectedItem();
    }
    
    public void setDoctors(DefaultComboBoxModel <Doctor> model){
        AdminDoctorFeedBackDoctorBox.setModel(model);
    }
    
    public void addChangeDoctor (ActionListener listenForDoctorChange)
    {
        AdminDoctorFeedBackDoctorBox.addActionListener(listenForDoctorChange);
    }
    
    public void setAdminDoctorFeedBackBox(String feedback){
        AdminDoctorFeedBackBox.setText(feedback);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBackButton;
    private javax.swing.JTextArea AdminDoctorFeedBackBox;
    private javax.swing.JComboBox<Doctor> AdminDoctorFeedBackDoctorBox;
    private javax.swing.JLabel AdminDoctorFeedBackLabel;
    private javax.swing.JButton AdminDoctorFeedBackSubmitButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
