/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Admin;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import models.Rating;
import models.user.Doctor;

/**
 *
 * @author richa_bfe6tpy
 */
//This class provide a panel which contains the Admin View ratings view.
public class AdminViewRatingsView extends javax.swing.JPanel {

    /**
     * Creates new form AdminViewRatingsView
     */
    public AdminViewRatingsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AdminViewRatingsListBox = new javax.swing.JList<>();
        AdminViewRatingsLabel = new javax.swing.JLabel();
        AdminViewRatingsDoctorsBox = new javax.swing.JComboBox<>();
        AdminSubmitButton = new javax.swing.JButton();

        AdminBackButton.setText("Back");

        AdminViewRatingsListBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(AdminViewRatingsListBox);

        AdminViewRatingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminViewRatingsLabel.setText("Doctor ratings");

        AdminSubmitButton.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AdminBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdminSubmitButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(AdminViewRatingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(AdminViewRatingsDoctorsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(AdminViewRatingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(AdminViewRatingsDoctorsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminBackButton)
                    .addComponent(AdminSubmitButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //Button Listeners
    public void addBackListener(ActionListener listenForBack){
        AdminBackButton.addActionListener(listenForBack);
    }
    
    public void addSubmitListener(ActionListener listenForSubmit){
        AdminSubmitButton.addActionListener(listenForSubmit);
    }
    
    //setup for ratings list box
    
    public void setRatings(DefaultListModel<Rating> ratings)
    {
        AdminViewRatingsListBox.setModel(ratings);
    }
    
    public void clearRatingsList (){
        AdminViewRatingsListBox.removeAll();
    }
    
    //setup for doctor list box
    
    public void clearDoctorList (){
        AdminViewRatingsDoctorsBox.removeAll();
    }
    
    public void setDoctors(DefaultComboBoxModel<Doctor> doctors)
    {
        AdminViewRatingsDoctorsBox.setModel(doctors);
    }
    
    //get that returns selected doctor
    
     public Doctor getDoctor(){
        return (Doctor) AdminViewRatingsDoctorsBox.getSelectedItem();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBackButton;
    private javax.swing.JButton AdminSubmitButton;
    private javax.swing.JComboBox<Doctor> AdminViewRatingsDoctorsBox;
    private javax.swing.JLabel AdminViewRatingsLabel;
    private javax.swing.JList<Rating> AdminViewRatingsListBox;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
