/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Doctor;

import java.awt.event.ActionListener;

/**
 *
 * @author richa_bfe6tpy
 */
//This class provide a panel which contains the Doctor create new medicine view.

public class DoctorCreateNewMedicineView extends javax.swing.JPanel {

    /**
     * Creates new form DoctorCreateNewMedicineView
     */
    public DoctorCreateNewMedicineView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorCreateMedicineHeaderLabel = new javax.swing.JLabel();
        DoctorCreateMedicineField = new javax.swing.JTextField();
        DoctorCreateMedicineLabel = new javax.swing.JLabel();
        DoctorSubmitButton = new javax.swing.JButton();
        DoctorBackButton = new javax.swing.JButton();

        DoctorCreateMedicineHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DoctorCreateMedicineHeaderLabel.setText("Create A New Medicine ");

        DoctorCreateMedicineLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DoctorCreateMedicineLabel.setText("Enter New Medicine Name:");

        DoctorSubmitButton.setText("Submit");

        DoctorBackButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorCreateMedicineHeaderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DoctorCreateMedicineLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DoctorBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DoctorSubmitButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(DoctorCreateMedicineField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(DoctorCreateMedicineHeaderLabel)
                .addGap(80, 80, 80)
                .addComponent(DoctorCreateMedicineLabel)
                .addGap(18, 18, 18)
                .addComponent(DoctorCreateMedicineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorSubmitButton)
                    .addComponent(DoctorBackButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //Button Listeners
    public void addSubmitListener(ActionListener listenForSubmit){
        DoctorSubmitButton.addActionListener(listenForSubmit);
    }
    
    public void addBackListener(ActionListener listenForBack){
        DoctorBackButton.addActionListener(listenForBack);
    }
    
    //get create medicine field
    
    public String getDoctorCreateMedicineField (){
        return DoctorCreateMedicineField.getText();
    }
    
    //clear create medicine field
    
    public void clearDoctorCreateMedicineField(){
        DoctorCreateMedicineField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorBackButton;
    private javax.swing.JTextField DoctorCreateMedicineField;
    private javax.swing.JLabel DoctorCreateMedicineHeaderLabel;
    private javax.swing.JLabel DoctorCreateMedicineLabel;
    private javax.swing.JButton DoctorSubmitButton;
    // End of variables declaration//GEN-END:variables
}
