/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Doctor;

import java.awt.event.ActionListener;

/**
 *
 * @author richa_bfe6tpy
 */
//This class provide a panel which contains the Main Doctor Control Panel view.
public class DoctorView extends javax.swing.JPanel {

    /**
     * Creates new form DoctorView2
     */
    public DoctorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorViewPatientHistoryButton = new javax.swing.JButton();
        DoctorCreateMedicineButton = new javax.swing.JButton();
        DoctorStartAppointmentButton = new javax.swing.JButton();
        DoctorViewAppointmentsButton = new javax.swing.JButton();
        DoctorLogoutButton = new javax.swing.JButton();
        DoctorCreatePerscriptionButton = new javax.swing.JButton();
        DoctorPanelLabel = new javax.swing.JLabel();

        DoctorViewPatientHistoryButton.setText("View Patient History");

        DoctorCreateMedicineButton.setText("Create Medicine");

        DoctorStartAppointmentButton.setText("Start Appointment");

        DoctorViewAppointmentsButton.setText("View Appointments ");

        DoctorLogoutButton.setText("Logout");

        DoctorCreatePerscriptionButton.setText("Create Perscription");

        DoctorPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DoctorPanelLabel.setText("Doctor Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorPanelLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DoctorLogoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DoctorCreatePerscriptionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoctorStartAppointmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoctorViewPatientHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DoctorCreateMedicineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoctorViewAppointmentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DoctorLogoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(DoctorPanelLabel)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorStartAppointmentButton)
                    .addComponent(DoctorViewAppointmentsButton))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorViewPatientHistoryButton)
                    .addComponent(DoctorCreateMedicineButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoctorCreatePerscriptionButton)
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Button Listeners 
    public void addStartAppointmentListener(ActionListener listenForStartAppointment){
        DoctorStartAppointmentButton.addActionListener(listenForStartAppointment);
    }
    
    public void addViewPatientHistoryListener(ActionListener listenForViewPatientHistory){
        DoctorViewPatientHistoryButton.addActionListener(listenForViewPatientHistory);
    }
    
    public void addCreateNewMedicineListener(ActionListener listenForCreateNewMedicine){
        DoctorCreateMedicineButton.addActionListener(listenForCreateNewMedicine);
    }
    
    public void addViewAppointmentListener(ActionListener listenForViewAppointment){
        DoctorViewAppointmentsButton.addActionListener(listenForViewAppointment);
    }
    
    public void addCreatePerscriptionListener(ActionListener listenForCreatePerscription){
        DoctorCreatePerscriptionButton.addActionListener(listenForCreatePerscription);
    }
    
    public void addLogoutListener(ActionListener listenForLogout){
        DoctorLogoutButton.addActionListener(listenForLogout);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorCreateMedicineButton;
    private javax.swing.JButton DoctorCreatePerscriptionButton;
    private javax.swing.JButton DoctorLogoutButton;
    private javax.swing.JLabel DoctorPanelLabel;
    private javax.swing.JButton DoctorStartAppointmentButton;
    private javax.swing.JButton DoctorViewAppointmentsButton;
    private javax.swing.JButton DoctorViewPatientHistoryButton;
    // End of variables declaration//GEN-END:variables
}
