/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Doctor;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;
import models.Appointment;
import models.user.Patient;

/**
 *
 * @author richa_bfe6tpy
 */
public class DoctorViewPatientView extends javax.swing.JPanel {

    /**
     * Creates new form DoctorViewPatient
     */
    public DoctorViewPatientView() {
        initComponents();
        DoctorViewPatientHistoryList.setCellRenderer(createListRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorViewPatientHistoryPatientBox = new javax.swing.JComboBox<>();
        DoctorViewPatientHistoryLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoctorViewPatientHistoryList = new javax.swing.JList<>();
        DoctorBackButton = new javax.swing.JButton();
        DoctorViewPatientSelectButton = new javax.swing.JButton();

        DoctorViewPatientHistoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DoctorViewPatientHistoryLabel.setText("View Patient History");

        DoctorViewPatientHistoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(DoctorViewPatientHistoryList);

        DoctorBackButton.setText("Back");

        DoctorViewPatientSelectButton.setText("Select");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorViewPatientHistoryLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(DoctorViewPatientHistoryPatientBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DoctorBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DoctorViewPatientSelectButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(DoctorViewPatientHistoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoctorViewPatientHistoryPatientBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorBackButton)
                    .addComponent(DoctorViewPatientSelectButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void addSelectListener(ActionListener listenForSelect){
        DoctorViewPatientSelectButton.addActionListener(listenForSelect);
    }
    
    public void addBackListener(ActionListener listenForBack){
        DoctorBackButton.addActionListener(listenForBack);
    }
    
    public void setDoctorViewPatientHistoryPatientBox(DefaultComboBoxModel<Patient> model)
    {
        DoctorViewPatientHistoryPatientBox.setModel(model);
    }
    
    public Patient getDoctorViewPatientHistoryPatientBox()
    {
        return (Patient) DoctorViewPatientHistoryPatientBox.getSelectedItem();
    }
    
    public void setDoctorViewPatientHistoryList(DefaultListModel<Appointment> model)
    {
        DoctorViewPatientHistoryList.setModel(model);
    }
    
    private static ListCellRenderer<? super Appointment> createListRenderer() {
      return new DefaultListCellRenderer() {
          private Color background = new Color(0, 100, 255, 15);
          private Color defaultBackground = (Color) UIManager.get("List.background");
          
          public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                                                        boolean isSelected, boolean cellHasFocus) {
              Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
              if (c instanceof JLabel) {
                  JLabel label = (JLabel) c;
                  Appointment app = (Appointment) value;
                  label.setText(String.format("Date:%s         Comments:%s",app.getAppointmentDate().toString(),app.getComments()));
                  if (!isSelected) {
                      label.setBackground(index % 2 == 0 ? background : defaultBackground);
                  }
              }
              return c;
          }
      };
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorBackButton;
    private javax.swing.JLabel DoctorViewPatientHistoryLabel;
    private javax.swing.JList<Appointment> DoctorViewPatientHistoryList;
    private javax.swing.JComboBox<Patient> DoctorViewPatientHistoryPatientBox;
    private javax.swing.JButton DoctorViewPatientSelectButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
